version: '3.8'
services: 
  ps2dev: 
    build: 
      context: . 
      dockerfile: Dockerfile
    volumes: 
      - ..:/workspace:cached
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "18193:18193/tcp"
      - "18193:18193/udp"
      - "18194:18194/tcp"
      - "18194:18194/udp"